<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Seed/records.json" LogicalName="EmrDemo.Core.Seed.records.json" />
    <EmbeddedResource Include="Seed/forms.json" LogicalName="EmrDemo.Core.Seed.forms.json" />
  </ItemGroup>

</Project>
