<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>EmrDemo</AssemblyName>
    <RequireAdmin Condition="'$(RequireAdmin)' == ''">false</RequireAdmin>
    <ApplicationManifest Condition="'$(RequireAdmin)' == 'true'">app.admin.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../EmrDemo.Core/EmrDemo.Core.csproj" />
  </ItemGroup>

</Project>
